"""Sources tab: every typed input (blue/red) across the engine tabs, with its label, evidence label and source note. Generated by scanning, so no input can exist without a row."""
from .common import *
TABS = ['E1 Fleet', 'E2 Claims & Totals', 'E3 Carriers', 'E4 Aftermarket', 'E5 Prices & Fees', 'E6 Other Branches', 'Scenarios', 'RPM']
def build(wb, ctx):
    ws = wb.create_sheet('Sources'); tab_color(ws, NAVY); setup(ws, label_w=22, ncols=6, notes_col='I')
    title(ws, 'Sources — every typed number in the model, with its label and where it comes from', 'Generated from the engine tabs at build time. Blue = input, red = toggle. A row with an empty source is a defect; Checks counts them.')
    for j, h in enumerate(['Tab', 'Cell', 'Row label', 'Value', 'Evidence label', 'Source / rationale']): put(ws, f'{L(2+j)}4', h, 'label', b=True)
    ws.column_dimensions['D'].width = 60; ws.column_dimensions['E'].width = 12; ws.column_dimensions['F'].width = 13; ws.column_dimensions['G'].width = 90
    r = 5; missing = []
    for name in TABS:
        if name not in wb.sheetnames: continue
        t = wb[name]; ncol = NOTES_COL.get(name, 'P' if name == 'RPM' else 'S')
        for row in t.iter_rows(min_row=3, max_row=t.max_row):
            for c in row:
                if isinstance(c.value, (int, float)) and not isinstance(c.value, bool) and c.font and c.font.color is not None and c.font.color.rgb in (f'00{C_INPUT}', f'FF{C_INPUT}', C_INPUT, f'00{C_TOGGLE}', f'FF{C_TOGGLE}', C_TOGGLE):
                    lab = t[f'B{c.row}'].value or t[f'B{c.row - 1}'].value or ''; ev = t[f'E{c.row}'].value if isinstance(t[f'E{c.row}'].value, str) and t[f'E{c.row}'].value.isupper() else ''
                    note = t[f'{ncol}{c.row}'].value or ''
                    if not note and name == 'Scenarios': note = 'Case parameter (toggle) — see Scenarios case definitions'
                    if not note and name == 'RPM' and c.coordinate == 'D3': note = 'Scenario selector (1–7), see label in B3'
                    NOTES_COL.setdefault('RPM', 'P')
                    if not note and name == 'E2 Claims & Totals' and 7 <= c.row <= 12: note = 'Fiscal-quarter interpolation weight, MEASURED by rule (common.py cy_weights)'
                    if not note and name == 'E4 Aftermarket' and c.row in (7, 8): note = 'Sourcing path value; see Inputs rows'
                    put(ws, f'B{r}', name, 'label'); put(ws, f'C{r}', c.coordinate, 'label'); put(ws, f'D{r}', str(lab)[:120], 'label'); put(ws, f'E{r}', c.value, 'input' if c.font.color.rgb.endswith(C_INPUT) else 'toggle'); put(ws, f'F{r}', ev, 'note'); put(ws, f'G{r}', str(note)[:400], 'note')
                    if not note: missing.append(f'{name}!{c.coordinate}')
                    r += 1
    ctx['sources_missing'] = len(missing); ctx['sources_missing_list'] = missing
    put(ws, f'B{r+1}', f'{r-5} typed inputs; {len(missing)} without a source note.', 'label', b=True); ws.freeze_panes = 'B5'
