import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const dir=path.dirname(fileURLToPath(import.meta.url)),out=process.env.CPRT_OUTPUT_DIR||(path.basename(dir)==='work'?path.dirname(dir):dir);
const d=JSON.parse(await fs.readFile(path.join(dir,'model_inputs.json'),'utf8'));
const wb=Workbook.create();
const names=['RPM Summary','Volume Build','Vehicle Economics','Revenue Bridge','CALCULATIONS','Cohort Roll','Repair Costs','Loss Calibration','Fee Calculation','DATA','AD Financials','AD Fleet','AD Repair','AD Fees & TLF'];
const s=Object.fromEntries(names.map(n=>[n,wb.worksheets.add(n)]));
const C=n=>String.fromCharCode(65+n),body=['Car','SUV / crossover','Pickup','Van'],years=[2023,2024,2025,2026,2027];
const fmt='#,##0.0;(#,##0.0);"-"',pct='0.00%;(0.00%);"-"',ratio='0.000"x"',navy='#153650',line='#9A9A9A',light='#E8E8E8';
function V(n,a,v){s[n].getRange(a).values=[[v]];}
function F(n,a,f){s[n].getRange(a).formulas=[[f]];s[n].getRange(a).format.font.color=n==='RPM Summary'?'#000000':f.includes('!')?'#008000':'#000000';}
function L(n,r,t){V(n,'C'+r,t);}
function box(n,r,t,end='K'){L(n,r,t);s[n].getRange(`C${r}:${end}${r}`).format={fill:light,font:{bold:true},borders:{top:{style:'thin',color:line},bottom:{style:'thin',color:line}},rowHeight:21};}
function total(n,r,end='K'){s[n].getRange(`C${r}:${end}${r}`).format={font:{bold:true},borders:{top:{style:'thin',color:navy},bottom:{style:'double',color:navy}}};}
function note(n,r,t,end='K',height=28){V(n,'C'+r,t);s[n].getRange(`C${r}:${end}${r}`).merge();s[n].getRange(`C${r}:${end}${r}`).format={wrapText:true,font:{size:10,color:'#555555'},rowHeight:height};}
function base(n,title,sub,last=45,end='M'){
 const q=s[n];q.showGridLines=false;q.getRange(`A1:${end}${last}`).format={font:{name:'Garamond',size:12},rowHeight:18,verticalAlignment:'center'};
 q.getRange(`A1:B${last}`).format.columnWidth=1.5;q.getRange(`C1:C${last}`).format.columnWidth=45;q.getRange(`D1:${end}${last}`).format.columnWidth=13;
 q.getRange(`D6:${end}${last}`).setNumberFormat(fmt);V(n,'C2',title);q.getRange('C2:K2').merge();q.getRange('C2:K2').format={font:{bold:true,size:15},rowHeight:24};note(n,3,sub);
 q.freezePanes.freezeRows(6);q.freezePanes.freezeColumns(3);
}
function head(n,r,arr,start=2){const rg=s[n].getRangeByIndexes(r-1,start,1,arr.length);rg.values=[arr];rg.format={fill:light,font:{bold:true},wrapText:true,rowHeight:29,borders:{top:{style:'thin',color:line},bottom:{style:'thin',color:line}}};}
function Q(n,periods){head(n,5,['Fiscal quarter',...periods.map(p=>p.label)]);L(n,6,'Quarter ending');periods.forEach((p,i)=>{V(n,C(i+3)+'6',new Date(p.end+'T12:00:00Z'));s[n].getRange(C(i+3)+'6').setNumberFormat('mmm-yy');});}
function raw(n,range,vals){s[n].getRange(range).values=vals;s[n].getRange(range).format.font.color='#0000FF';}
function input(n,cell,v,format=fmt){V(n,cell,v);s[n].getRange(cell).format={font:{color:'#FF0000'},fill:'#FFF5D6'};s[n].getRange(cell).setNumberFormat(format);}
const front=d.periods.slice(4),cohort=(b,a)=>42+b*46+a,fr=(b,a)=>8+b*46+a;

base('AD Financials','Reported service revenue ($m)','FY25 comparatives and FY26 actuals, from the four FY26 earnings releases. Values only.',24);Q('AD Financials',d.periods.slice(0,8));
for(const[r,l]of [[8,'US services'],[9,'International services'],[10,'Total service revenue']])L('AD Financials',r,l);
d.actuals.forEach((a,i)=>{const c=C(i+3);raw('AD Financials',c+'8',[[a.us_service]]);raw('AD Financials',c+'9',[[a.intl_service]]);raw('AD Financials',c+'10',[[a.us_service+a.intl_service]]);});total('AD Financials',10);
box('AD Financials',12,'Source documents');d.source_paths.forEach((p,i)=>note('AD Financials',13+i,p,'K',23));note('AD Financials',18,'Local archived SEC release paths above. Latest: https://www.sec.gov/Archives/edgar/data/900075/000119312526387902/cprt-ex99_1.htm');

base('AD Fleet','Fleet source records','Car/LT births, EPA survival and calendar timing weights. Forecasts and fitted adjustments belong in the build.',67);
head('AD Fleet',5,['Year','Cars (000s)','LT (000s)']);raw('AD Fleet','C6:E61',d.sales.map(r=>[+r.year,+r.cars_k,+r.light_trucks_k]));s['AD Fleet'].getRange('C1:C67').format.columnWidth=13;s['AD Fleet'].getRange('C6:C61').setNumberFormat('0');
head('AD Fleet',5,['Age','Car survival','LT survival'],6);raw('AD Fleet','G6:I37',d.survival.map(r=>[+r.age,+r.survival_cars,+r.survival_light_trucks]));s['AD Fleet'].getRange('G6:G37').setNumberFormat('0');s['AD Fleet'].getRange('H6:I37').setNumberFormat(pct);
head('AD Fleet',44,['Period',...years],5);s['AD Fleet'].getRange('G44:K44').setNumberFormat('0');raw('AD Fleet','F46:K57',d.periods.map(p=>[p.label.replace(/A$/,'M'),...p.weights]));s['AD Fleet'].getRange('G46:K57').setNumberFormat(pct);s['AD Fleet'].getRange('F1:F67').format.columnWidth=17;
note('AD Fleet',63,'Sources: data/csv/light_vehicle_sales_by_year.csv and ornl_tedb40_survival_by_age.csv in cprt-research. Ward’s/ORNL; later sales rescaled from FRED.','M');note('AD Fleet',65,'Timing weights average three monthly midpoints interpolated between calendar-year-end stocks. They are a timing convention, not observed quarterly claims.','M');

base('AD Repair','Repair evidence','CRSS police-crash involvement mix; AAA hypothetical complete estimates; CCC repairable-cost benchmark. Values only.',45);
head('AD Repair',5,['Body','Age','Sample N','Front share','Rear share','Front SE','Rear SE']);raw('AD Repair','C6:I25',d.crss.map(r=>[r.body,r.age,+r.sample_n,+r.front_share,+r.rear_share,+r.front_se,+r.rear_se]));s['AD Repair'].getRange('F6:I25').setNumberFormat(pct);s['AD Repair'].getRange('E6:E25').setNumberFormat('#,##0');
head('AD Repair',30,['AAA scope','Camry ($)','Rogue ($)','F150 ($)']);raw('AD Repair','C31:F34',d.aaa.rows.map(r=>[r.scope,r.camry,r.rogue,r.f150]));
L('AD Repair',38,'CCC 7+ repairable mean ($)');raw('AD Repair','D38',[[3682]]);head('AD Repair',39,['Listing weights',...body]);raw('AD Repair','D40:G40',[[0,.409,.109,.047]]);s['AD Repair'].getRange('D40:G40').setNumberFormat(pct);
note('AD Repair',27,'CRSS2024: cohort_table.csv in repair_frequency_feasibility. Shares are survey estimates of initial impact in police crashes, not paid-claim repair frequencies.');
note('AD Repair',36,'AAA2023 report: newsroom.aaa.com/wp-content/uploads/2023/11/Report_Cost-of-ADAS-Repairs-FINAL-23.pdf. F150 detail/summary discrepancy remains unresolved.');
note('AD Repair',42,'CCC Crash Course 2026 older-vehicle repair mean is assigned to cars by assumption. Listing weights are a Jan-2026 proxy, not historical exposure weights.');

const fees=d.fees.filter(r=>r.page==='non-licensed'&&r.title_group==='non-clean'&&r.vehicle_class==='standard'&&r.fee_type==='buyer_fee'&&r.payment_method==='secured');
const virtual=d.fees.filter(r=>r.page==='non-licensed'&&r.title_group==='non-clean'&&r.vehicle_class==='standard'&&r.fee_type==='virtual_bid_pre_bid');
base('AD Fees & TLF','Total-loss and fee sources','CCC2025 age buckets and the September-2026 buyer fee schedule. One buyer tier; values only.',78);
head('AD Fees & TLF',5,['Age bucket','CCC2025 TLF']);raw('AD Fees & TLF','C6:D12',d.ccc.map(r=>[r.age_bucket,+r.cy2025/100]));s['AD Fees & TLF'].getRange('D6:D12').setNumberFormat(pct);
note('AD Fees & TLF',14,'CCC Crash Course 2026, Figure 19: cccis.com/reports/crash-course-2026. Bucket calibration does not validate the modeled body split.');
head('AD Fees & TLF',18,['Bid lower ($)','Fixed fee ($)','Rate']);raw('AD Fees & TLF',`C19:E${18+fees.length}`,fees.map(r=>[+r.band_low_usd,+(r.fee_usd||0),+(r.fee_pct||0)/100]));s['AD Fees & TLF'].getRange(`E19:E${18+fees.length}`).setNumberFormat(pct);
head('AD Fees & TLF',18,['Prebid lower ($)','Fee ($)'],6);raw('AD Fees & TLF',`G19:H${18+virtual.length}`,virtual.map(r=>[+r.band_low_usd,+r.fee_usd]));V('AD Fees & TLF','G30','Gate fee');raw('AD Fees & TLF','H30',[[95]]);V('AD Fees & TLF','G31','Environment');raw('AD Fees & TLF','H31',[[15]]);
note('AD Fees & TLF',71,'Copart US non-licensed / non-clean / standard / secured / prebid: copart.com/content/us/en/member-fees-us-non-licensed. Saved 26-Sep-2026.','M');note('AD Fees & TLF',73,'Environmental $15 comes from the archived page text. Fee percentages are converted from 7.5 percentage points to 0.075. Other services and actual buyer-tier mix are not modeled.','M');

base('Repair Costs','Repair-cost calculation','Live reconstruction of the authorized working case. Population and scope transfers remain assumptions.',37);head('Repair Costs',5,['Input / calculation',...body]);
for(const[r,l]of [[7,'Front impact weight'],[8,'Rear impact weight'],[9,'Other impact weight'],[10,'Weight sum'],[12,'Front cost / same-scope car'],[13,'Rear cost / same-scope car'],[14,'Other cost / same-scope car'],[16,'Car repair mean anchor ($)'],[17,'Car rear / front scope cost'],[18,'Car other / front scope cost'],[19,'Car front mean scale ($)'],[21,'Front mean repair cost ($)'],[22,'Rear mean repair cost ($)'],[23,'Other mean repair cost ($)'],[25,'Weighted mean repair cost ($)'],[26,'Repair cost / car'],[28,'Raw LT listing weights'],[29,'Normalized within-LT weights'],[31,'Blended LT repair mean ($)'],[32,'LT repair premium']])L('Repair Costs',r,l);
for(let b=0;b<4;b++){const c=C(3+b),row=6+d.crss.findIndex(r=>r.body===['Car','SUV','Pickup','Minivan'][b]&&r.age==='7-9');F('Repair Costs',c+'7',`='AD Repair'!F${row}`);F('Repair Costs',c+'8',`='AD Repair'!G${row}`);F('Repair Costs',c+'9',`=1-SUM(${c}7:${c}8)`);F('Repair Costs',c+'10',`=SUM(${c}7:${c}9)`);
 const ac=b===0?'D':b===2?'F':'E';F('Repair Costs',c+'12',`='AD Repair'!${ac}31/'AD Repair'!$D$31`);F('Repair Costs',c+'13',`='AD Repair'!${ac}33/'AD Repair'!$D$33`);input('Repair Costs',c+'14',[1,1.1,1.15,1.1][b],ratio);
 F('Repair Costs',c+'21',`=$D$19*${c}12`);F('Repair Costs',c+'22',`=$D$19*$D$17*${c}13`);F('Repair Costs',c+'23',`=$D$19*$D$18*${c}14`);F('Repair Costs',c+'25',`=SUMPRODUCT(${c}7:${c}9,${c}21:${c}23)`);F('Repair Costs',c+'26',`=${c}25/$D$25`);F('Repair Costs',c+'28',`='AD Repair'!${c}40`);F('Repair Costs',c+'29',`=${c}28/SUM($E$28:$G$28)`);
}F('Repair Costs','D16',"='AD Repair'!D38");input('Repair Costs','D17',.6,ratio);input('Repair Costs','D18',.8,ratio);F('Repair Costs','D19','=D16/(D7+D8*D17+D9*D18)');F('Repair Costs','D31','=SUMPRODUCT(E25:G25,E29:G29)');F('Repair Costs','D32','=D31/D25-1');
for(const rg of ['D7:G10','D28:G29','D32'])s['Repair Costs'].getRange(rg).setNumberFormat(pct);for(const rg of ['D12:G14','D26:G26'])s['Repair Costs'].getRange(rg).setNumberFormat(ratio);total('Repair Costs',25,'G');note('Repair Costs',34,'AAA new-car ratios are transferred to older cohorts; other-scope premiums are assumed. Vans use SUV scope ratios. CRSS impact mix is transferred to claims.');

base('Vehicle Economics','Vehicle economics','Read across bodies: repair cost versus net totaling threshold, then auction price and service fees.',35);head('Vehicle Economics',5,['Economics',...body]);
for(const[r,l]of [[7,'ACV / same-age car'],[8,'Gross salvage / ACV'],[9,'Seller fee / auction price'],[10,'Relative claim frequency'],[12,'Modeled mean repair cost ($)'],[13,'Repair cost / car'],[14,'Net salvage / ACV'],[15,'Net totaling threshold / car'],[16,'Probit offset: ln(threshold / repair) / σ'],[26,'Age-10 auction price ($)'],[27,'Age-10 service RPU ($)']])L('Vehicle Economics',r,l);
for(let b=0;b<4;b++){const c=C(3+b);input('Vehicle Economics',c+'7',b?1.5:1,ratio);input('Vehicle Economics',c+'8',.3,pct);input('Vehicle Economics',c+'9',.04,pct);input('Vehicle Economics',c+'10',1,ratio);F('Vehicle Economics',c+'12',`='Repair Costs'!${c}25`);F('Vehicle Economics',c+'13',`=${c}12/$D$12`);F('Vehicle Economics',c+'14',`=${c}8*(1-${c}9)`);F('Vehicle Economics',c+'15',`=${c}7*(1-${c}14)/($D$7*(1-$D$14))`);F('Vehicle Economics',c+'16',`=LN(${c}15/${c}13)/$J$8`);F('Vehicle Economics',c+'26',`='Fee Calculation'!E${fr(b,10)}`);F('Vehicle Economics',c+'27',`='Fee Calculation'!M${fr(b,10)}`);}
head('Vehicle Economics',5,['Common inputs','Value'],8);for(const[r,l,v,fmtx]of [[8,'Dispersion σ',d.repair.inherited_sigma,'0.000'],[9,'Car age-10 ACV',10000,fmt],[10,'ACV age decay',.1,pct]]){V('Vehicle Economics','I'+r,l);input('Vehicle Economics','J'+r,v,fmtx);}
head('Vehicle Economics',12,['Bid node','Mean ×','Weight'],8);[.5,1,1.5].forEach((v,i)=>{V('Vehicle Economics','I'+(13+i),['Low','Central','High'][i]);input('Vehicle Economics','J'+(13+i),v,'0.00"x"');input('Vehicle Economics','K'+(13+i),[.25,.5,.25][i],pct);});s['Vehicle Economics'].getRange('I1:I35').format.columnWidth=20;
box('Vehicle Economics',18,'Calibrated total-loss probability','G');['Current year','Age 1–3','Age 4–6','Age 7–9','Age 10–12','Age 13+'].forEach((l,k)=>{L('Vehicle Economics',19+k,l);for(let b=0;b<4;b++)F('Vehicle Economics',C(3+b)+(19+k),`='Loss Calibration'!${C(4+b)}${8+k}`);});
s['Vehicle Economics'].getRange('D19:G24').setNumberFormat(pct);s['Vehicle Economics'].getRange('D13:G15').setNumberFormat(ratio);s['Vehicle Economics'].getRange('D14:G14').setNumberFormat(pct);s['Vehicle Economics'].getRange('D16:G16').setNumberFormat('0.000');total('Vehicle Economics',12,'G');total('Vehicle Economics',27,'G');
note('Vehicle Economics',29,'Red = assumption. ACV ratios and recovery assumptions are unvalidated. Net salvage subtracts the modeled seller fee only. Matching CCC buckets is calibration, not validation.');note('Vehicle Economics',31,'The same-age fee comparison is illustrative. Fee Calculation prices each cohort at three auction nodes; the Volume Build uses the resulting sold-unit-weighted mix.');

base('Volume Build','Auction volume build','Modeled historical periods and forecast periods. Growth contributions—not absolute Copart auction counts.',32);Q('Volume Build',front.map(p=>({...p,label:p.label.replace(/A$/,'M')})));
for(const[r,l]of [[8,'Average fleet vehicles (000s)'],[9,'Fleet growth, YoY'],[11,'Weighted claim exposure growth, YoY'],[12,'Modeled total-loss frequency'],[13,'Auction-volume contribution, YoY'],[15,'Service RPU ($, modeled)'],[16,'Composition contribution to RPU, YoY'],[17,'Combined demographic revenue effect'],[22,'Car survival stretch'],[23,'LT survival stretch'],[24,'Claim-weight decay after age 6'],[25,'New-cohort exposure fraction']])L('Volume Build',r,l);
input('Volume Build','D22',1.270,'0.000');input('Volume Build','D23',1.099,'0.000');input('Volume Build','D24',.09027,'0.00000');input('Volume Build','D25',.5,pct);box('Volume Build',20,'Fitted age-profile inputs');note('Volume Build',27,'Survival stretches and claim decay are inherited fits. Future births / LT share are editable in Cohort Roll. No independent absolute claims or company-unit estimate is implied.');

base('Cohort Roll','Cohort roll and fiscal-quarter timing','Live survival, claim weights, total-loss calibration and fees. Historical periods marked M are modeled.',230,'O');Q('Cohort Roll',d.periods.map(p=>({...p,label:p.label.replace(/A$/,'M')})));
for(const[r,l]of [[8,'Fleet stock (000s)'],[9,'Weighted claim exposure'],[10,'Weighted sale exposure'],[11,'Weighted fee exposure'],[13,'Fleet growth, YoY'],[14,'Claim exposure growth, YoY'],[15,'Modeled total-loss frequency'],[16,'Auction-volume contribution, YoY'],[17,'Modeled service RPU ($)'],[18,'Composition contribution to RPU, YoY'],[19,'Demographic revenue effect, YoY']])L('Cohort Roll',r,l);
box('Cohort Roll',21,'Calendar-year-end cohort engine');head('Cohort Roll',22,['Calendar year',...years]);s['Cohort Roll'].getRange('D22:H22').setNumberFormat('0');L('Cohort Roll',26,'New vehicles (000s)');L('Cohort Roll',27,'LT share of new vehicles');
for(let j=0;j<5;j++){const c=C(3+j),r=6+years[j]-1970;if(j<3){F('Cohort Roll',c+'26',`=SUM('AD Fleet'!D${r}:E${r})`);F('Cohort Roll',c+'27',`='AD Fleet'!E${r}/${c}26`);}else{F('Cohort Roll',c+'26',`=${C(2+j)}26`);F('Cohort Roll',c+'27',`=${C(2+j)}27`);}}s['Cohort Roll'].getRange('G26:H27').format.fill='#FFF5D6';s['Cohort Roll'].getRange('D27:H27').setNumberFormat(pct);
for(const[r,l]of [[30,'Vehicles (000s)'],[31,'Claim exposure'],[32,'Sale exposure'],[33,'Fee exposure']])L('Cohort Roll',r,l);
for(let j=0;j<5;j++){const c=C(j+3);F('Cohort Roll',c+'30',`=SUM(${c}42:${c}225)`);F('Cohort Roll',c+'31',`=SUMPRODUCT(${c}42:${c}225,$O$42:$O$225)`);F('Cohort Roll',c+'32',`=SUMPRODUCT(${c}42:${c}225,$O$42:$O$225,$J$42:$J$225)`);F('Cohort Roll',c+'33',`=SUMPRODUCT(${c}42:${c}225,$O$42:$O$225,$J$42:$J$225,$I$42:$I$225)`);}
note('Cohort Roll',35,'Quarter stocks average three monthly midpoints between calendar-year-end stocks. Same-quarter prior-year reported service revenue supplies financial seasonality.','O');
head('Cohort Roll',40,['Body / age',...years,'Service RPU','TL probability','Body','Age','Bucket','Survival','Claim weight']);s['Cohort Roll'].getRange('D40:H40').setNumberFormat('0');
for(let b=0;b<4;b++)for(let a=0;a<46;a++){const r=cohort(b,a),bc=C(b+3),k=a===0?1:a<=3?2:a<=6?3:a<=9?4:a<=12?5:6,stretch=b?'$D$23':'$D$22',rawcol=b?'I':'H',z=`($L${r}/'Volume Build'!${stretch})`;
 L('Cohort Roll',r,`${body[b]} / ${a}`);V('Cohort Roll','K'+r,body[b]);V('Cohort Roll','L'+r,a);V('Cohort Roll','M'+r,k);
 F('Cohort Roll','N'+r,`=IF(${z}>=31,0,INDEX('AD Fleet'!$${rawcol}$6:$${rawcol}$37,INT(${z})+1)+(${z}-INT(${z}))*(INDEX('AD Fleet'!$${rawcol}$6:$${rawcol}$37,MIN(INT(${z})+2,32))-INDEX('AD Fleet'!$${rawcol}$6:$${rawcol}$37,INT(${z})+1)))`);
 F('Cohort Roll','O'+r,`=IF(L${r}=0,'Volume Build'!$D$25,1)*EXP(-'Volume Build'!$D$24*MAX(L${r}-6,0))*'Vehicle Economics'!${bc}$10`);F('Cohort Roll','J'+r,`=INDEX('Loss Calibration'!$E$8:$H$13,M${r},${b+1})`);F('Cohort Roll','I'+r,`='Fee Calculation'!M${fr(b,a)}`);
 for(let j=0;j<5;j++){const c=C(j+3),v=years[j]-a;let births;if(v<=2025){const sc=b?'E':'D';births=`INDEX('AD Fleet'!$${sc}$6:$${sc}$61,MATCH(${v},'AD Fleet'!$C$6:$C$61,0))`;}else{const yc=C(v-2023+3);births=`${yc}$26*${b?`${yc}$27`:`(1-${yc}$27)`}`;}const split=b?`*'Repair Costs'!${bc}$29`:'';F('Cohort Roll',c+r,`=${births}${split}*$N${r}`);}
}
s['Cohort Roll'].getRange('J42:J225').setNumberFormat(pct);s['Cohort Roll'].getRange('L42:M225').setNumberFormat('0');s['Cohort Roll'].getRange('N42:O225').setNumberFormat(pct);
for(let j=0;j<12;j++){const c=C(j+3),wr=46+j;for(const[r,ar]of [[8,30],[9,31],[10,32],[11,33]])F('Cohort Roll',c+r,`=SUMPRODUCT($D$${ar}:$H$${ar},'AD Fleet'!G${wr}:K${wr})`);F('Cohort Roll',c+'15',`=${c}10/${c}9`);F('Cohort Roll',c+'17',`=${c}11/${c}10`);if(j<4){for(const r of [13,14,16,18,19])V('Cohort Roll',c+r,'n.a.');}else{const py=C(j-1);F('Cohort Roll',c+'13',`=${c}8/${py}8-1`);F('Cohort Roll',c+'14',`=${c}9/${py}9-1`);F('Cohort Roll',c+'16',`=${c}10/${py}10-1`);F('Cohort Roll',c+'18',`=${c}17/${py}17-1`);F('Cohort Roll',c+'19',`=(1+${c}16)*(1+${c}18)-1`);}}
for(const r of [13,14,15,16,18,19])s['Cohort Roll'].getRange(`D${r}:O${r}`).setNumberFormat(pct);
for(let j=0;j<8;j++){const c=C(j+3),sc=C(j+7);for(const[r,src]of [[8,8],[9,13],[11,14],[12,15],[13,16],[15,17],[16,18],[17,19]])F('Volume Build',c+r,`='Cohort Roll'!${sc}${src}`);}for(const r of [9,11,12,13,16,17])s['Volume Build'].getRange(`D${r}:K${r}`).setNumberFormat(pct);total('Volume Build',13);total('Volume Build',17);

base('Loss Calibration','CCC age-bucket calibration','Solve one common index per age bucket; retain body offsets from repair/value economics. No hidden solver or macro.',260,'L');head('Loss Calibration',5,['Age bucket','CCC target',...body,'Blended','Difference']);
const buckets=['Current year','1–3','4–6','7–9','10–12','13+'];head('Loss Calibration',17,['2025 claim weights',...body,'Total']);
for(let k=0;k<6;k++){const r=18+k;L('Loss Calibration',r,buckets[k]);for(let b=0;b<4;b++){const lo=cohort(b,0),hi=cohort(b,45);F('Loss Calibration',C(3+b)+r,`=SUMPRODUCT('Cohort Roll'!$F$${lo}:$F$${hi},'Cohort Roll'!$O$${lo}:$O$${hi},--('Cohort Roll'!$M$${lo}:$M$${hi}=${k+1}))`);}F('Loss Calibration','H'+r,`=SUM(D${r}:G${r})`);}
note('Loss Calibration',25,'P(body, bucket) = NORMDIST(common index − body offset, 0, 1, TRUE). Weighted mean equals the CCC2025 target using modeled 2025 claim exposures.');
for(let k=0;k<6;k++){const top=28+k*37,w=18+k;box('Loss Calibration',top,`${buckets[k]}: bisection solve`,'L');head('Loss Calibration',top+1,['Iteration','Lower','Upper','Index','Car P','SUV P','Pickup P','Van P','Weighted P','Target']);
 for(let it=0;it<32;it++){const r=top+2+it;V('Loss Calibration','C'+r,it+1);if(!it){V('Loss Calibration','D'+r,-8);V('Loss Calibration','E'+r,8);}else{F('Loss Calibration','D'+r,`=IF(K${r-1}<L${r-1},F${r-1},D${r-1})`);F('Loss Calibration','E'+r,`=IF(K${r-1}<L${r-1},E${r-1},F${r-1})`);}F('Loss Calibration','F'+r,`=(D${r}+E${r})/2`);for(let b=0;b<4;b++)F('Loss Calibration',C(6+b)+r,`=NORMDIST($F${r}-'Vehicle Economics'!$${C(3+b)}$16,0,1,TRUE)`);F('Loss Calibration','K'+r,`=SUMPRODUCT(G${r}:J${r},$D$${w}:$G$${w})/$H$${w}`);F('Loss Calibration','L'+r,`='AD Fees & TLF'!$D$${6+k}`);}
 const r=8+k,last=top+33;L('Loss Calibration',r,buckets[k]);F('Loss Calibration','D'+r,`='AD Fees & TLF'!D${6+k}`);for(let b=0;b<4;b++)F('Loss Calibration',C(4+b)+r,`=${C(6+b)}${last}`);F('Loss Calibration','I'+r,`=K${last}`);F('Loss Calibration','J'+r,`=I${r}-D${r}`);
}s['Loss Calibration'].getRange('D8:J13').setNumberFormat(pct);s['Loss Calibration'].getRange('D30:L249').setNumberFormat('0.0000');

base('Fee Calculation','Nonlinear fee calculation','ACV → gross auction proceeds → buyer fees at three price nodes → weighted fee plus seller fee.',196);
head('Fee Calculation',5,['Body / age','ACV ($)','Mean bid','Low bid','Mid bid','High bid','Low fee','Mid fee','High fee','Buyer fee','Service RPU']);
for(let b=0;b<4;b++)for(let a=0;a<46;a++){const r=fr(b,a),bc=C(b+3);L('Fee Calculation',r,`${body[b]} / ${a}`);F('Fee Calculation','D'+r,`='Vehicle Economics'!$J$9*EXP(-'Vehicle Economics'!$J$10*(${a}-10))*'Vehicle Economics'!${bc}$7`);F('Fee Calculation','E'+r,`=D${r}*'Vehicle Economics'!${bc}$8`);
 for(let k=0;k<3;k++){const bid=C(5+k),fee=C(8+k);F('Fee Calculation',bid+r,`=$E${r}*'Vehicle Economics'!$J$${13+k}`);F('Fee Calculation',fee+r,`=VLOOKUP(${bid}${r},'AD Fees & TLF'!$C$19:$E$${18+fees.length},2,TRUE)+${bid}${r}*VLOOKUP(${bid}${r},'AD Fees & TLF'!$C$19:$E$${18+fees.length},3,TRUE)+VLOOKUP(${bid}${r},'AD Fees & TLF'!$G$19:$H$${18+virtual.length},2,TRUE)+SUM('AD Fees & TLF'!$H$30:$H$31)`);}
 F('Fee Calculation','L'+r,`=I${r}*'Vehicle Economics'!$K$13+J${r}*'Vehicle Economics'!$K$14+K${r}*'Vehicle Economics'!$K$15`);F('Fee Calculation','M'+r,`=L${r}+E${r}*'Vehicle Economics'!${bc}$9`);
}note('Fee Calculation',194,'One current buyer tier is applied consistently across periods to isolate composition. Actual buyer mix, ancillary services and calendar price inflation are not modeled.','M');

base('Revenue Bridge','Quarterly service-revenue bridge ($m)','Same-quarter prior-year actuals provide seasonality. Fleet contribution replaces the effect embedded in the baseline.',38,'L');Q('Revenue Bridge',front);
box('Revenue Bridge',7,'Forecast drivers');for(const[r,l]of [[8,'US service growth before fleet change'],[9,'International service growth'],[10,'US service exposed to insured fleet'],[13,'Prior-year US service revenue'],[14,'US revenue at baseline growth'],[15,'Fleet effect in latest reported quarter'],[16,'Fleet effect in projected quarter'],[17,'Incremental fleet adjustment ($m)'],[18,'US service revenue'],[21,'Prior-year international services'],[22,'International service revenue'],[24,'Total service revenue'],[25,'Service revenue growth, YoY']])L('Revenue Bridge',r,l);
box('Revenue Bridge',12,'US service revenue');box('Revenue Bridge',20,'International service revenue');
for(let j=0;j<8;j++){const c=C(j+3),py=C(j+3),actual=C(j+7);F('Revenue Bridge',c+'13',`='AD Financials'!${py}8`);F('Revenue Bridge',c+'21',`='AD Financials'!${py}9`);
 if(j<4){F('Revenue Bridge',c+'8',`='AD Financials'!${actual}8/'AD Financials'!${py}8-1`);F('Revenue Bridge',c+'9',`='AD Financials'!${actual}9/'AD Financials'!${py}9-1`);V('Revenue Bridge',c+'10','n.a.');F('Revenue Bridge',c+'18',`='AD Financials'!${actual}8`);F('Revenue Bridge',c+'22',`='AD Financials'!${actual}9`);for(const r of [14,15,16,17])V('Revenue Bridge',c+r,'n.a.');}
 else{F('Revenue Bridge',c+'8','=$G$8');F('Revenue Bridge',c+'9','=$G$9');if(j===4)input('Revenue Bridge',c+'10',.9,pct);else F('Revenue Bridge',c+'10','=$H$10');F('Revenue Bridge',c+'14',`=${c}13*(1+${c}8)`);F('Revenue Bridge',c+'15',"='Volume Build'!$G$17");F('Revenue Bridge',c+'16',`='Volume Build'!${c}17`);F('Revenue Bridge',c+'17',`=${c}14/(1+${c}10*${c}15)*${c}10*(${c}16-${c}15)`);F('Revenue Bridge',c+'18',`=${c}14+${c}17`);F('Revenue Bridge',c+'22',`=${c}21*(1+${c}9)`);}
 F('Revenue Bridge',c+'24',`=${c}18+${c}22`);F('Revenue Bridge',c+'25',`=${c}24/'AD Financials'!${py}10-1`);
}for(const r of [8,9,10,15,16,25])s['Revenue Bridge'].getRange(`D${r}:K${r}`).setNumberFormat(pct);s['Revenue Bridge'].getRange('H8:K10').format.fill='#FFF5D6';total('Revenue Bridge',18);total('Revenue Bridge',24);
note('Revenue Bridge',27,'US forecast = baseline revenue × (1 + exposure × projected fleet growth) / (1 + exposure × reference fleet growth). This avoids adding the same fleet effect twice.');
note('Revenue Bridge',29,'Growth inputs default to latest reported YoY rates, not consensus. 90% insured-service exposure is assumed. Carrier contracts, fees, catastrophe and FX need separate forecast judgments.');
box('Revenue Bridge',31,'Reconciliation checks');L('Revenue Bridge',32,'Service components / reported gap');L('Revenue Bridge',33,'Price weights / mean-node gap');L('Revenue Bridge',34,'Largest CCC calibration gap');
for(let j=0;j<8;j++){const c=C(j+3);F('Revenue Bridge',c+'32',j<4?`=${c}24-'AD Financials'!${C(j+7)}10`:`=${c}24-${c}18-${c}22`);}F('Revenue Bridge','D33',"=SUM('Vehicle Economics'!K13:K15)-1");F('Revenue Bridge','E33',"=SUMPRODUCT('Vehicle Economics'!J13:J15,'Vehicle Economics'!K13:K15)-1");F('Revenue Bridge','D34',"=MAX('Loss Calibration'!J8:J13,-MIN('Loss Calibration'!J8:J13))");s['Revenue Bridge'].getRange('D32:K34').setNumberFormat('0.000000');

base('RPM Summary','Copart service revenue projection ($m)','Four main reading tabs; supporting calculations and source data follow. Six-month focus: Q1 / Q2 FY27.',25,'L');Q('RPM Summary',front);V('RPM Summary','L5','H1 FY27E');V('RPM Summary','L6','Next two quarters');s['RPM Summary'].getRange('L1:L25').format.columnWidth=18;
box('RPM Summary',7,'Service revenue','L');for(const[r,l,br]of [[8,'US service revenue',18],[9,'International service revenue',22],[10,'Total service revenue',24],[11,'Service revenue growth, YoY',25]]){L('RPM Summary',r,l);for(let j=0;j<8;j++){const c=C(j+3);F('RPM Summary',c+r,`='Revenue Bridge'!${c}${br}`);}F('RPM Summary','L'+r,r===11?'=L10/SUM(D10:E10)-1':`=SUM(H${r}:I${r})`);}s['RPM Summary'].getRange('D11:L11').setNumberFormat(pct);total('RPM Summary',10,'L');s['RPM Summary'].getRange('C10:L10').format.fill='#E9E1ED';
box('RPM Summary',13,'Fleet contribution to the projection','L');for(const[r,l,vr]of [[14,'Auction-volume growth contribution',13],[15,'Composition contribution to RPU',16],[16,'Combined demographic revenue effect',17]]){L('RPM Summary',r,l);for(let j=0;j<8;j++)F('RPM Summary',C(j+3)+r,`='Volume Build'!${C(j+3)}${vr}`);}s['RPM Summary'].getRange('D14:K16').setNumberFormat(pct);L('RPM Summary',18,'Incremental fleet adjustment ($m)');for(let j=0;j<8;j++)F('RPM Summary',C(j+3)+'18',`='Revenue Bridge'!${C(j+3)}17`);F('RPM Summary','L18','=SUM(H18:I18)');
note('RPM Summary',20,'Standalone Copart service revenue; pending ACV excluded. Latest-growth starting case with an incremental fleet adjustment, not a consensus-derived earnings forecast.','L');
note('RPM Summary',22,'Read: Volume Build for cohorts → Vehicle Economics for repair/value/fees → Revenue Bridge for quarterly dollars. Red inputs are assumptions; blue values are source records.','L');

for(const[n,t,links]of [['CALCULATIONS','Supporting calculations',['Cohort Roll','Repair Costs','Loss Calibration','Fee Calculation']],['DATA','Source data',['AD Financials','AD Fleet','AD Repair','AD Fees & TLF']]]){base(n,t,'Section divider. Supporting schedules remain visible and contain native Excel formulas where applicable.',12);links.forEach((l,i)=>L(n,5+i,l));}
s['RPM Summary'].tabColor=navy;s.CALCULATIONS.tabColor='#A6A6A6';s.DATA.tabColor='#548235';
// Compact financial tables: rules delineate sections, rows and the actual/forecast boundary.
for(const n of ['RPM Summary','Volume Build','Revenue Bridge']){s[n].getRange('H5:H25').format.borders={left:{style:'thin',color:navy}};s[n].getRange('H5:I6').format.fill='#E5EDF4';}
for(const[n,rows,end]of [['RPM Summary',[8,9,14,15,16,18],'L'],['Volume Build',[8,9,11,12,15,16,22,23,24,25],'K'],['Vehicle Economics',[7,8,9,10,12,13,14,15,16,19,20,21,22,23,24,26,27],'G'],['Revenue Bridge',[8,9,10,13,14,15,16,17,21,22,25],'K']])for(const r of rows)s[n].getRange(`C${r}:${end}${r}`).format.borders={bottom:{style:'hair',color:'#D4D4D4'}};
for(const n of names)s[n].getRange('C5:C40').format.wrapText=true;
s['Vehicle Economics'].getRange('C16:G16').format.rowHeight=28;
wb.recalculate();
const read=()=>s['RPM Summary'].getRange('H8:L11').values;const before=read();const calibrationBefore=s['Loss Calibration'].getRange('E8:H13').values;
input('Vehicle Economics','E7',1.2,ratio);wb.recalculate();const changed=read();const calibrationChanged=s['Loss Calibration'].getRange('E8:H13').values;input('Vehicle Economics','E7',1.5,ratio);wb.recalculate();if(JSON.stringify(before)===JSON.stringify(changed)||JSON.stringify(calibrationBefore)===JSON.stringify(calibrationChanged)||JSON.stringify(before)!==JSON.stringify(read()))throw new Error('Live ACV/calibration test failed');
input('Repair Costs','F14',1.3,ratio);wb.recalculate();const repairChanged=read();input('Repair Costs','F14',1.15,ratio);wb.recalculate();if(JSON.stringify(before)===JSON.stringify(repairChanged)||JSON.stringify(before)!==JSON.stringify(read()))throw new Error('Repair propagation test failed');
input('Revenue Bridge','H10',0,pct);wb.recalculate();const zeroExposure=s['Revenue Bridge'].getRange('H17').values[0][0];input('Revenue Bridge','H10',.9,pct);wb.recalculate();if(Math.abs(zeroExposure)>1e-10||JSON.stringify(before)!==JSON.stringify(read()))throw new Error('Exposure propagation test failed');
await fs.writeFile(path.join(dir,'live_model_tests.json'),JSON.stringify({before,changed,repairChanged,zeroExposure,restored:read()},null,2));
await fs.mkdir(path.join(out,'preview_live'),{recursive:true});for(const n of names){const range=n==='RPM Summary'?'C2:L23':n==='Vehicle Economics'?'C2:K32':n==='Volume Build'?'C2:K28':n==='Revenue Bridge'?'C2:K34':n==='Repair Costs'?'C2:K35':n==='AD Fleet'?'C2:K23':n==='AD Repair'?'C2:K43':n==='Loss Calibration'?'C2:L25':n==='Fee Calculation'?'C2:M23':n==='Cohort Roll'?'C2:O22':n==='CALCULATIONS'||n==='DATA'?'C2:K9':'C2:K23';const blob=await wb.render({sheetName:n,range,scale:1.5,format:'png'});await fs.writeFile(path.join(out,'preview_live',n.replaceAll(' ','_')+'.png'),new Uint8Array(await blob.arrayBuffer()));}
const file=await SpreadsheetFile.exportXlsx(wb);await file.save(path.join(out,'CPRT_Fleet_and_Body_Mix.xlsx'));
console.log(JSON.stringify({tabs:names,serviceRevenue:s['RPM Summary'].getRange('H10:L10').values,repairCosts:s['Repair Costs'].getRange('D25:G25').values,calibrationGap:s['Revenue Bridge'].getRange('D34').values}));
